
name: Capture Plugin
on: [push, pull_request]

jobs:

  macos:
    strategy:
      matrix:
        target: [macos-universal]
    runs-on: macos-13
    steps:
      - name: dummy screenshot
        run: |
          open ~
          sleep 2
          screencapture screenshot.jpg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot1
          path: ./screenshot.jpg
